### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by MStrecke** [cmlburnett/PyDvdRead#1]
I tried to install pydvdread via pip, which did fail because `src/dvdread.h` is missing in **their** ZIP file.

I then downloaded `dvdread.h` from here, put it into the "pip-ZIP" and tried again.
I got several error messages complaining about not being in C99 mode.

Then I tried the ZIP from the current master here.
Same result.

As far as my research shows, it seems that the compiler option `-std=c99` is missing.
However, I don't know what to change in the package to make it add that option when compiling the C part.

**Comment by MStrecke** [comment]
Fixes in https://github.com/cmlburnett/PyDvdRead/pull/2

**Comment by cmlburnett** [comment]
Thanks!
